name: Deploy Azure Resources

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: "Name of the Resource Group"
        required: true
        default: "default-rg"
      location:
        description: "Azure Region for Resources"
        required: true
        default: "eastus"

jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure CLI
        run: |
          # Login using a predefined Azure identity (managed or local credentials)
          az login --allow-no-subscriptions
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Service Principal
        id: sp-create
        run: |
          # Create a service principal with the Contributor role
          SP_OUTPUT=$(az ad sp create-for-rbac --role Contributor --scopes /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }} --query "{clientId: appId, clientSecret: password, tenantId: tenant, subscriptionId: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'}" -o json)
          
          # Save the credentials for subsequent steps
          echo "${SP_OUTPUT}" > sp.json
          echo "SP_CREDS=$(cat sp.json)" >> $GITHUB_ENV
          
      - name: Authenticate with Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ env.SP_CREDS }}

      - name: Deploy Azure Resources
        run: |
          # Use Azure CLI to deploy resources
          az group create --name ${{ github.event.inputs.resource_group }} --location ${{ github.event.inputs.location }}
          echo "Resource group deployed successfully!"

