name: Deploy Azure Resources

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: "Name of the Resource Group"
        required: true
        default: "default-rg"
      location:
        description: "Azure Region for Resources"
        required: true
        default: "eastus"
      environment_setup:
        description: "Create a new environment setup"
        required: true
        default: "false"
      environment:
        description: "Environment name"
        required: true
        default: "dev"

jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set User Inputs as Environment Variables
        run: |
          echo "RESOURCE_GROUP=${{ github.event.inputs.resource_group }}" >> $GITHUB_ENV
          echo "LOCATION=${{ github.event.inputs.location }}" >> $GITHUB_ENV
          echo "ENVIRONMENT_SETUP=${{ github.event.inputs.environment_setup }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Deploy Azure Resources
        run: |
          function deploy_resource_group() {
            az group create --name "$RESOURCE_GROUP" --location "$LOCATION"
          }

          function deploy_app() {
            APP_NAME="${RESOURCE_GROUP}-app"
            APP_ID=$(az ad app create --display-name "$APP_NAME" --query appId -o tsv)
            SP_SECRET=$(az ad sp create --id "$APP_ID" --query password -o tsv)
            echo "Service Principal App ID: $APP_ID"
            echo "Service Principal Secret: $SP_SECRET"
          }

          deploy_resource_group
          deploy_app
