name: Deploy Azure Resources

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: "Name of the Resource Group"
        required: true
        default: "tv-infra"
      location:
        description: "Azure Region for Resources"
        required: true
        default: "uksouth"
      environment_setup:
        description: "Create a new environment setup"
        required: true
        default: "false"
      environment:
        description: "Environment name"
        required: true
        default: "dev"

jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set User Inputs as Environment Variables
        run: |
          echo "RESOURCE_GROUP=${{ github.event.inputs.resource_group }}" >> $GITHUB_ENV
          echo "LOCATION=${{ github.event.inputs.location }}" >> $GITHUB_ENV
          echo "ENVIRONMENT_SETUP=${{ github.event.inputs.environment_setup }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Deploy Azure Resources
        run: |

          function deploy_keyvault() {
            PGSQL_PASSWORD=$(openssl rand -base64 32)
            echo "Deploying Key Vault..."
            keyvaultOutput=$(az deployment group create --resource-group $RESOURCE_GROUP \
              --template-file tv-infra-keyvault.json \
              --parameters location=$LOCATION environment=$ENVIRONMENT \
              pgDbPassword=$PGSQL_PASSWORD \
              --query "properties.outputs.keyVaultName-name.value" -o tsv)
            echo "KEYVAULT_NAME=${keyvaultOutput}" >> $GITHUB_ENV
          }

          function deploy_nsg() {
            echo "Deploying Network Security Group..."
            nsgOutput=$(az deployment group create --resource-group $RESOURCE_GROUP \
              --template-file tv-infra-nsg.json \
              --parameters location=$LOCATION environment=$ENVIRONMENT \
              --query "properties.outputs.nsg-name.value" -o tsv)
            echo "NSG_NAME=${nsgOutput}" >> $GITHUB_ENV
          }

          function deploy_vnet() {
            echo "Deploying Virtual Network..."
            vnetOutput=$(az deployment group create --resource-group $RESOURCE_GROUP \
              --template-file tv-infra-vnet.json \
              --parameters location=$LOCATION environment=$ENVIRONMENT \
              nsg-name=$NSG_NAME \
              --query "properties.outputs.vnet-name.value" -o tsv)
            echo "VNET_NAME=${vnetOutput}" >> $GITHUB_ENV
          }

          function deploy_postgres() {
            echo "Deploying PostgreSQL SERVER..."
            postgresOutput=$(az deployment group create --resource-group $RESOURCE_GROUP \
              --template-file tv-infra-postgres.json \
              --parameters location=$LOCATION environment=$ENVIRONMENT \
              --query "properties.outputs.postgres-server-name.value" -o tsv)
            echo "POSTGRES_SERVER_NAME=${postgresOutput}" >> $GITHUB_ENV
          }

          function deploy_storage() {
            echo "Deploying Storage Account..."
            storageOutput=$(az deployment group create --resource-group $RESOURCE_GROUP \
              --template-file tv-infra-storage.json \
              --parameters location=$LOCATION environment=$ENVIRONMENT \
              --query "properties.outputs.storage-account-name.value" -o tsv)
            echo "STORAGE_ACCOUNT_NAME=${storageOutput}" >> $GITHUB_ENV
          }

          function deploy_acr() {
            echo "Deploying Azure Container Registry..."
            acrOutput=$(az deployment group create --resource-group $RESOURCE_GROUP \
              --template-file tv-infra-acr.json \
              --parameters location=$LOCATION environment=$ENVIRONMENT \
              --query "properties.outputs.acr-name.value" -o tsv)
            echo "ACR_NAME=${acrOutput}" >> $GITHUB_ENV
          }

          function deploy_comm_service() {
            echo "Deploying Communication Service..."
            commServiceOutput=$(az deployment group create --resource-group $RESOURCE_GROUP \
              --template-file tv-infra-comm-service.json \
              --parameters environment=$ENVIRONMENT \
              --query "properties.outputs.comm-service-name.value" -o tsv)
            echo "COMM_SERVICE_NAME=${commServiceOutput}" >> $GITHUB_ENV
          }

          function deploy_maps_account() {
            echo "Deploying Maps Account..."
            mapsAccountOutput=$(az deployment group create --resource-group $RESOURCE_GROUP \
              --template-file tv-infra-maps-account.json \
              --parameters environment=$ENVIRONMENT \
              --query "properties.outputs.maps-account-name.value" -o tsv)
            echo "MAPS_ACCOUNT_NAME=${mapsAccountOutput}" >> $GITHUB_ENV
          }

          function deploy_app_service_plan() {
            echo "Deploying App Service Plan..."
            appServicePlanOutput=$(az deployment group create --resource-group $RESOURCE_GROUP \
              --template-file tv-infra-service.json \
              --parameters location=$LOCATION environment=$ENVIRONMENT \
              --query "properties.outputs.app-service-plan-name.value" -o tsv)
            echo "APP_SERVICE_PLAN_NAME=${appServicePlanOutput}" >> $GITHUB_ENV
          }

          if [ "$ENVIRONMENT_SETUP" = "true" ]; then
            deploy_resource_group
            deploy_keyvault
            deploy_nsg
            deploy_vnet
            deploy_postgres
            deploy_storage
            deploy_acr
            deploy_comm_service
            deploy_maps_account
            deploy_app_service_plan          
          fi

          declare -A expected_resources=(
            ["Microsoft.KeyVault/vaults"]="keyvaultOutput"
            ["Microsoft.DBforPostgreSQL/servers"]="postgresOutput"
            ["Microsoft.Network/virtualNetworks"]="vnetOutput"
            ["Microsoft.Network/networkSecurityGroups"]="nsgOutput"
            ["Microsoft.Storage/storageAccounts"]="storageOutput"
            ["Microsoft.ContainerRegistry/registries"]="acrOutput"
            ["Microsoft.Communication/CommunicationServices"]="commServiceOutput"
            ["Microsoft.Maps/accounts"]="mapsOutput"
            ["Microsoft.Web/serverfarms"]="appServicePlanOutput"
          )
          
          for type in "${!expected_resources[@]}"; do
            output_name=${expected_resources[$type]}
            
            # Assign the correct deployment name based on resource type
            case $type in
              "Microsoft.KeyVault/vaults")
                deployment_name="keyvault-deploy-${{ env.ENVIRONMENT }}"
                ;;
              "Microsoft.DBforPostgreSQL/servers")
                deployment_name="postgres-deploy-${{ env.ENVIRONMENT }}"
                ;;
              "Microsoft.Network/virtualNetworks")
                deployment_name="vnet-deploy-${{ env.ENVIRONMENT }}"
                ;;
              "Microsoft.Network/networkSecurityGroups")
                deployment_name="nsg-deploy-${{ env.ENVIRONMENT }}"
                ;;
              "Microsoft.Storage/storageAccounts")
                deployment_name="storage-deploy-${{ env.ENVIRONMENT }}"
                ;;
              "Microsoft.ContainerRegistry/registries")
                deployment_name="acr-deploy-${{ env.ENVIRONMENT }}"
                ;;
              "Microsoft.Communication/CommunicationServices")
                deployment_name="comm-service-deploy-${{ env.ENVIRONMENT }}"
                ;;
              "Microsoft.Maps/accounts")
                deployment_name="maps-account-deploy-${{ env.ENVIRONMENT }}"
                ;;
              "Microsoft.Web/serverfarms")
                deployment_name="app-service-plan-deploy-${{ env.ENVIRONMENT }}"
                ;;
              *)
                echo "Unknown resource type: $type"
                ;;
            esac
            
            # Get the resource ID using the deployment name
            resource_id=$(az deployment group show --resource-group $RESOURCE_GROUP --name $deployment_name --query "properties.outputs.$output_name.value" -o tsv)
          
            if [ -z "$resource_id" ]; then
              echo "Resource missing: Type=$type"
              # Deploy the missing resource
              case $type in
                "Microsoft.KeyVault/vaults")
                  deploy_keyvault
                  ;;
                "Microsoft.DBforPostgreSQL/servers")
                  deploy_postgres
                  ;;
                "Microsoft.Network/virtualNetworks")
                  deploy_vnet
                  ;;
                "Microsoft.Network/networkSecurityGroups")
                  deploy_nsg
                  ;;
                "Microsoft.Storage/storageAccounts")
                  deploy_storage
                  ;;
                "Microsoft.ContainerRegistry/registries")
                  deploy_acr
                  ;;
                "Microsoft.Communication/CommunicationServices")
                  deploy_comm_service
                  ;;
                "Microsoft.Maps/accounts")
                  deploy_maps_account
                  ;;
                "Microsoft.Web/serverfarms")
                  deploy_app_service_plan
                  ;;
                *)
                  echo "Unknown resource type: $type"
                  ;;
              esac
            else
              echo "Resource exists: Type=$type, ID=$resource_id"
            fi
          done        

